"""
Settings router - manage Subbrainarr and Subgen configuration
"""
from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional, List, Dict
import json
import os

router = APIRouter()

class PathMapping(BaseModel):
    host_path: str
    container_path: str

class LanguageConfig(BaseModel):
    patience: float
    length_penalty: float
    beam_size: int = 5

class SubgenSettings(BaseModel):
    subgen_url: str = "http://localhost:9000"
    whisper_model: str = "large-v3"
    compute_type: str = "float16"
    transcribe_device: str = "cuda"
    beam_size: int = 5
    whisper_threads: int = 4
    concurrent_transcriptions: int = 1
    clear_vram_on_complete: bool = True
    whisper_task: str = "translate"
    subtitle_language: str = "en"
    use_path_mapping: bool = False
    path_mapping: Optional[PathMapping] = None
    skip_if_english_audio: bool = True
    skip_if_english_subs_exist: bool = True
    skip_files_patterns: List[str] = ["subbed", "korsub", "dubbed"]
    auto_skip_threshold: float = 0.75
    ssa_fix_encoding: bool = True
    ssa_fix_newlines: bool = True
    custom_regroup: Optional[str] = None
    custom_env_vars: Dict[str, str] = {}
    language_configs: Dict[str, LanguageConfig] = {}

SETTINGS_FILE = "/app/config/settings.json"

def load_settings() -> SubgenSettings:
    """Load settings from file or return defaults"""
    try:
        if os.path.exists(SETTINGS_FILE):
            with open(SETTINGS_FILE, 'r') as f:
                data = json.load(f)
                return SubgenSettings(**data)
    except Exception as e:
        print(f"Error loading settings: {e}")
    
    return SubgenSettings()

def save_settings_to_file(settings: SubgenSettings):
    """Save settings to JSON file"""
    try:
        os.makedirs(os.path.dirname(SETTINGS_FILE), exist_ok=True)
        with open(SETTINGS_FILE, 'w') as f:
            json.dump(settings.dict(), f, indent=2)
        return True
    except Exception as e:
        print(f"Error saving settings: {e}")
        return False

def generate_compose_snippet(settings: SubgenSettings) -> str:
    """Generate docker-compose.yaml snippet for Subgen"""
    
    snippet = f"""# Subgen Configuration
# Generated by SubBrainArr - Copy and adapt as needed
# We're not your dad - take what you need and merge with your existing config

services:
  subgen:
    image: mccloud/subgen:latest
    container_name: subgen
    environment:
      # Model & Compute
      - WHISPER_MODEL={settings.whisper_model}
      - COMPUTE_TYPE={settings.compute_type}
      - TRANSCRIBE_DEVICE={settings.transcribe_device}
      
      # Performance
      - WHISPER_THREADS={settings.whisper_threads}
      - CONCURRENT_TRANSCRIPTIONS={settings.concurrent_transcriptions}
      - CLEAR_VRAM_ON_COMPLETE={'true' if settings.clear_vram_on_complete else 'false'}
      
      # Language & Task
      - WHISPER_TASK={settings.whisper_task}
      - SUBTITLE_LANGUAGE={settings.subtitle_language}
      
      # Skip Conditions
      - SKIP_IF_ENGLISH_AUDIO={'true' if settings.skip_if_english_audio else 'false'}
      - SKIP_IF_ENGLISH_SUBS_EXIST={'true' if settings.skip_if_english_subs_exist else 'false'}
      - SKIP_FILES_PATTERNS={','.join(settings.skip_files_patterns)}
      - AUTO_SKIP_THRESHOLD={settings.auto_skip_threshold}
      
      # Subtitle Fixes
      - SSA_FIX_ENCODING={'true' if settings.ssa_fix_encoding else 'false'}
      - SSA_FIX_NEWLINES={'true' if settings.ssa_fix_newlines else 'false'}"""
    
    if settings.custom_regroup:
        snippet += f"\n      - CUSTOM_REGROUP={settings.custom_regroup}"
    
    # Add per-language configurations
    if settings.language_configs:
        snippet += "\n      \n      # Per-Language Optimizations (SubBrainArr magic)"
        for lang_code, config in settings.language_configs.items():
            snippet += f"\n      - LANG_{lang_code.upper()}_PATIENCE={config.patience}"
            snippet += f"\n      - LANG_{lang_code.upper()}_LENGTH_PENALTY={config.length_penalty}"
            snippet += f"\n      - LANG_{lang_code.upper()}_BEAM_SIZE={config.beam_size}"
    
    # Add custom environment variables
    if settings.custom_env_vars:
        snippet += "\n      \n      # Your Custom Variables"
        for key, value in settings.custom_env_vars.items():
            snippet += f"\n      - {key}={value}"
    
    snippet += f"""
    
    volumes:
      - /path/to/config:/config"""
    
    if settings.use_path_mapping and settings.path_mapping:
        snippet += f"""
      - {settings.path_mapping.host_path}:{settings.path_mapping.container_path}"""
    else:
        snippet += """
      - /path/to/media:/media  # Update this path"""
    
    snippet += """
    
    ports:
      - "9000:9000"
    
    restart: unless-stopped

# After updating, restart Subgen:
#   docker compose down && docker compose up -d
"""
    
    return snippet

@router.get("/current", response_model=SubgenSettings)
async def get_current_settings():
    """Get current Subgen settings"""
    return load_settings()

@router.put("/update", response_model=SubgenSettings)
async def update_settings(settings: SubgenSettings):
    """Update and save Subgen settings"""
    success = save_settings_to_file(settings)
    
    if not success:
        return {"error": "Failed to save settings"}
    
    return settings

@router.get("/compose-snippet")
async def get_compose_snippet():
    """Get docker-compose.yaml snippet with current settings"""
    settings = load_settings()
    snippet = generate_compose_snippet(settings)
    
    return {
        "snippet": snippet,
        "settings": settings
    }

@router.get("/defaults")
async def get_default_settings():
    """Get recommended default settings"""
    return {
        "message": "Default settings based on detected hardware",
        "settings": SubgenSettings()
    }

@router.post("/test-path-mapping")
async def test_path_mapping(mapping: PathMapping):
    """Test if a path mapping is valid"""
    
    if not mapping.host_path or not mapping.container_path:
        return {
            "valid": False,
            "error": "Both paths are required"
        }
    
    container_exists = os.path.exists(mapping.container_path)
    
    return {
        "valid": container_exists,
        "host_path": mapping.host_path,
        "container_path": mapping.container_path,
        "container_exists": container_exists,
        "message": "Path exists in container" if container_exists else "Path not found in container"
    }