"""
Settings router - manage Subbrainarr and Subgen configuration
"""
from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional, List, Dict
import json
import os

router = APIRouter()

class PathMapping(BaseModel):
    host_path: str
    container_path: str

class LanguageConfig(BaseModel):
    patience: float
    length_penalty: float
    beam_size: int = 5

class SubgenSettings(BaseModel):
    subgen_url: str = "http://localhost:9000"
    whisper_model: str = "large-v3"
    compute_type: str = "float16"
    transcribe_device: str = "cuda"
    beam_size: int = 5
    whisper_threads: int = 4
    concurrent_transcriptions: int = 1
    clear_vram_on_complete: bool = True
    model_cleanup_delay: int = 30
    whisper_task: str = "translate"
    subtitle_language: str = "en"
    model_path: str = "./models"
    force_detected_language_to: str = ""
    monitor: bool = False
    transcribe_folders: List[str] = []
    use_path_mapping: bool = False
    path_mapping: Optional[PathMapping] = None
    skip_if_english_audio: bool = True
    skip_if_english_subs_exist: bool = True
    skip_files_patterns: List[str] = ["subbed", "korsub", "dubbed"]
    auto_skip_threshold: float = 0.75
    ssa_fix_encoding: bool = True
    ssa_fix_newlines: bool = True
    custom_regroup: Optional[str] = None
    custom_env_vars: Dict[str, str] = {}
    language_configs: Dict[str, LanguageConfig] = {}

SETTINGS_FILE = "/app/config/settings.json"

def load_settings() -> SubgenSettings:
    """Load settings from file or return defaults"""
    try:
        if os.path.exists(SETTINGS_FILE):
            with open(SETTINGS_FILE, 'r') as f:
                data = json.load(f)
                return SubgenSettings(**data)
    except Exception as e:
        print(f"Error loading settings: {e}")
    
    return SubgenSettings()

def save_settings_to_file(settings: SubgenSettings):
    """Save settings to JSON file"""
    try:
        os.makedirs(os.path.dirname(SETTINGS_FILE), exist_ok=True)
        with open(SETTINGS_FILE, 'w') as f:
            json.dump(settings.dict(), f, indent=2)
        return True
    except Exception as e:
        print(f"Error saving settings: {e}")
        return False

def _build_subgen_kwargs(settings: SubgenSettings) -> str:
    """Build SUBGEN_KWARGS value as Python dict syntax.

    Subgen parses this with its safe literal parser, so the output MUST be
    valid Python literal syntax. repr() on a dict produces exactly that.
    We never parse or execute this ourselves — it's a string for compose output.
    """
    kwargs: Dict = {}

    # Global beam_size — Subgen has NO standalone BEAM_SIZE env var,
    # it only reaches Whisper through SUBGEN_KWARGS
    kwargs["beam_size"] = settings.beam_size

    # If the selected subtitle language has tuning config, include it
    lang_code = settings.subtitle_language
    if lang_code and lang_code in settings.language_configs:
        lc = settings.language_configs[lang_code]
        kwargs["patience"] = lc.patience
        kwargs["length_penalty"] = lc.length_penalty
        # Per-language beam_size overrides global if explicitly different
        if lc.beam_size != settings.beam_size:
            kwargs["beam_size"] = lc.beam_size

    return repr(kwargs)


def generate_compose_snippet(settings: SubgenSettings) -> str:
    """Generate docker-compose.yaml snippet for Subgen"""

    snippet = f"""# Subgen Configuration
# Generated by SubBrainArr - Copy and adapt as needed
# We're not your dad - take what you need and merge with your existing config

services:
  subgen:
    image: mccloud/subgen:latest
    container_name: subgen
    environment:
      # Model & Compute
      - WHISPER_MODEL={settings.whisper_model}
      - COMPUTE_TYPE={settings.compute_type}
      - TRANSCRIBE_DEVICE={settings.transcribe_device}

      # Performance
      - WHISPER_THREADS={settings.whisper_threads}
      - CONCURRENT_TRANSCRIPTIONS={settings.concurrent_transcriptions}
      - CLEAR_VRAM_ON_COMPLETE={'true' if settings.clear_vram_on_complete else 'false'}"""

    # Model cleanup delay — only meaningful when VRAM clearing is enabled
    if settings.clear_vram_on_complete:
        snippet += f"\n      - MODEL_CLEANUP_DELAY={settings.model_cleanup_delay}"

    # Model storage path — only include when non-default
    if settings.model_path and settings.model_path != "./models":
        snippet += f"\n      - MODEL_PATH={settings.model_path}"

    snippet += f"""

      # Language & Task
      - TRANSCRIBE_OR_TRANSLATE={settings.whisper_task}
      - SUBTITLE_LANGUAGE={settings.subtitle_language}"""

    # Force language detection override
    if settings.force_detected_language_to:
        snippet += f"\n      - FORCE_DETECTED_LANGUAGE_TO={settings.force_detected_language_to}"

    snippet += f"""

      # Skip Conditions
      - SKIP_IF_ENGLISH_AUDIO={'true' if settings.skip_if_english_audio else 'false'}
      - SKIP_IF_ENGLISH_SUBS_EXIST={'true' if settings.skip_if_english_subs_exist else 'false'}
      - SKIP_FILES_PATTERNS={','.join(settings.skip_files_patterns)}
      - AUTO_SKIP_THRESHOLD={settings.auto_skip_threshold}

      # Subtitle Fixes
      - SSA_FIX_ENCODING={'true' if settings.ssa_fix_encoding else 'false'}
      - SSA_FIX_NEWLINES={'true' if settings.ssa_fix_newlines else 'false'}"""

    if settings.custom_regroup:
        snippet += f"\n      - CUSTOM_REGROUP={settings.custom_regroup}"

    # Whisper tuning — SUBGEN_KWARGS is the ONLY way to deliver beam_size,
    # patience, and length_penalty to Subgen. Uses Python dict syntax.
    kwargs_str = _build_subgen_kwargs(settings)
    snippet += f"""

      # Whisper Tuning (SUBGEN_KWARGS is Subgen's delivery mechanism)
      # Uses Python dict syntax, not JSON
      - SUBGEN_KWARGS={kwargs_str}"""

    # Folder monitoring
    if settings.monitor and settings.transcribe_folders:
        snippet += f"""

      # Folder Monitoring
      - MONITOR=true
      - TRANSCRIBE_FOLDERS={'|'.join(settings.transcribe_folders)}"""

    # Custom environment variables
    if settings.custom_env_vars:
        snippet += "\n\n      # Your Custom Variables"
        for key, value in settings.custom_env_vars.items():
            snippet += f"\n      - {key}={value}"

    snippet += """

    volumes:
      - /path/to/config:/config"""

    if settings.use_path_mapping and settings.path_mapping:
        snippet += f"""
      - {settings.path_mapping.host_path}:{settings.path_mapping.container_path}"""
    else:
        snippet += """
      - /path/to/media:/media  # Update this path"""

    snippet += """

    ports:
      - "9000:9000"

    restart: unless-stopped

# After updating, restart Subgen:
#   docker compose down && docker compose up -d
"""

    return snippet

@router.get("/current", response_model=SubgenSettings)
async def get_current_settings():
    """Get current Subgen settings"""
    return load_settings()

@router.put("/update", response_model=SubgenSettings)
async def update_settings(settings: SubgenSettings):
    """Update and save Subgen settings"""
    success = save_settings_to_file(settings)
    
    if not success:
        return {"error": "Failed to save settings"}
    
    return settings

@router.get("/compose-snippet")
async def get_compose_snippet():
    """Get docker-compose.yaml snippet with current settings"""
    settings = load_settings()
    snippet = generate_compose_snippet(settings)
    
    return {
        "snippet": snippet,
        "settings": settings
    }

@router.get("/defaults")
async def get_default_settings():
    """Get recommended default settings"""
    return {
        "message": "Default settings based on detected hardware",
        "settings": SubgenSettings()
    }

@router.post("/test-path-mapping")
async def test_path_mapping(mapping: PathMapping):
    """Test if a path mapping is valid"""
    
    if not mapping.host_path or not mapping.container_path:
        return {
            "valid": False,
            "error": "Both paths are required"
        }
    
    container_exists = os.path.exists(mapping.container_path)
    
    return {
        "valid": container_exists,
        "host_path": mapping.host_path,
        "container_path": mapping.container_path,
        "container_exists": container_exists,
        "message": "Path exists in container" if container_exists else "Path not found in container"
    }