blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/coaxk/subbrainarr/discussions
    about: Ask questions and discuss SubBrainArr in GitHub Discussions
